#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t morphos"

$L "    __  ___                 __    ____  _____"
$L "   /  |/  /___  _________  / /_  / __ \/ ___/"
$L "  / /|_/ / __ \/ ___/ __ \/ __ \/ / / /\__ \ "
$L " / /  / / /_/ / /  / /_/ / / / / /_/ /___/ / "
$L "/_/  /_/\____/_/  / .___/_/ /_/\____//____/  "
$L "                 /_/                         "
$L "Welcome to Android `getprop ro.build.version.release` / MorphOS-`getprop ro.morphos.version`";
